x-common: &common
  env_file:
    - .env.prod
  restart: unless-stopped

services:
  website:
    <<: [*common]
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - PYPI_MIRROR=https://mirrors.cloud.tencent.com/pypi/simple
      #   - SOURCES_MIRROR=mirrors.cloud.tencent.com
      #   - SECURITY_SOURCE_MIRROR=mirrors.cloud.tencent.com
      # args:
      #   - PYPI_MIRROR=https://mirrors.tencentyun.com/pypi/simple/
      #   - SOURCES_MIRROR=mirrors.tencentyun.com
      #   - SECURITY_SOURCE_MIRROR=mirrors.tencentyun.com
    image: website
    volumes:
      - staticfiles-data:/var/www/static
      - .:/website
    depends_on:
      - postgres
      - redis
    command: ./scripts/start_prod_server.sh

  proxy:
    <<: [*common]
    image: nginx:alpine-slim
    volumes:
      - type: volume
        source: staticfiles-data
        target: /usr/share/nginx/html/static
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: website.conf
        target: /etc/nginx/conf.d/website.conf
    depends_on:
      - website

  celery-worker:
    <<: [*common]
    image: website
    volumes:
      - .:/website
    depends_on:
      - website
    command: ./scripts/run_celery_worker.sh

  celery-beat:
    <<: [*common]
    image: website
    volumes:
      - .:/website
    depends_on:
      - website
    command: ./scripts/run_celery_beat.sh

  pgadmin:
    <<: [*common]
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres

  redis:
    <<: [*common]
    image: redis:alpine
    volumes:
      - redis-data:/data

  postgres:
    <<: [*common]
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  cloudflare-tunnel:
    <<: *common
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token <token>

volumes:
  staticfiles-data:
  postgres-data:
  redis-data:
