x-common: &common
  network_mode: service:app

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  postgres:
    <<: [*common]
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data

  redis:
    <<: [*common]
    image: redis:alpine
    volumes:
      - dev-redis-data:/data

volumes:
  dev-postgres-data:
  dev-redis-data:
