x-common: &common
  env_file:
    - .env
  restart: unless-stopped

services:
  redis:
    <<: *common
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - dev-redis-data:/data

  postgres:
    <<: *common
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data

volumes:
  dev-postgres-data:
  dev-redis-data:
